feat: update identity payout address
dashpay/dash-evo-tool pull request #123
Opened 2024-12-04 22:27 UTC by ogabrielides

2024-12-06 06:13 UTC, pauldelucia commented
The button is way too big 😄

2024-12-06 09:58 UTC, pauldelucia requested changes
The button is way too big 😄

2024-12-09 10:21 UTC, pauldelucia requested changes

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +    fn render_selected_wallet_funding_addresses(&mut self, ctx: &Context, ui: &mut Ui) {
```suggestion
    fn render_selected_wallet_funding_addresses(&mut self, ui: &mut Ui) {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +    fn render_selected_wallet_payout_addresses(&mut self, ctx: &Context, ui: &mut Ui) {
```suggestion
    fn render_selected_wallet_payout_addresses(&mut self, ui: &mut Ui) {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +            if (self.identity.identity_type == IdentityType::User) {
```suggestion
            if self.identity.identity_type == IdentityType::User {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +            if (!self.app_context.has_wallet.load(Ordering::Relaxed)) {
```suggestion
            if !self.app_context.has_wallet.load(Ordering::Relaxed) {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +                self.render_selected_wallet_payout_addresses(ctx, &mut ui);
```suggestion
                self.render_selected_wallet_payout_addresses(&mut ui);
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +                    self.render_selected_wallet_funding_addresses(ctx, &mut ui);
```suggestion
                    self.render_selected_wallet_funding_addresses(&mut ui);
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +    fn display_message(&mut self, message: &str, _message_type: MessageType) {
```suggestion
    fn display_message(&mut self, message: &str, message_type: MessageType) {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +        if _message_type == MessageType::Error {
```suggestion
        if message_type == MessageType::Error {
```

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +            self.render_wallet_selection(&mut ui);
I think you should render wallet unlock here as well after a wallet is selected, otherwise there will be an error when they try to update

2024-12-09 10:21 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +    fn display_message(&mut self, message: &str, _message_type: MessageType) {
I suggest using an UpdatePayoutAddressStatus enum for the screen and doing display_message like is done in other screens, such as register_dpns_name_screen.rs

2024-12-09 10:28 UTC, pauldelucia commented on src/ui/identities/update_identity_payout_address.rs
> +                        }
I'm pretty sure this will just make the error message flash for a millisecond

2024-12-10 16:46 UTC, thephez commented
This will only work for MNs that have their owner key in Dash Core (vs DMT) and in the specific wallet they connect to DET, correct?

2024-12-11 04:51 UTC, pauldelucia approved these changes
LGTM

I can't really test it though - I'm afraid to do anything with the testnet MNs/HPMNs. Did you test it?

Also, preferably I think we should add a success screen (for example like after creating an identity) rather than just PopScreenAndRefresh.

2024-12-11 08:08 UTC, ogabrielides commented
> This will only work for MNs that have their owner key in Dash Core (vs DMT) and in the specific wallet they connect to DET, correct?

@thephez Correct!

2026-03-31 18:48 UTC, thepastaclaw requested changes
<!-- thepastaclaw-review v1 sha=e4c299f71cf23d5a5d2b715c785b8ba968061187 -->
## Code Review

PR adds identity payout address update via protx update_registrar RPC. Both agents independently found a critical parameter mapping bug: the payout address is sent in the voting-address slot and the funding address in the payout slot, making the feature non-functional as written.

*Reviewed commit: e4c299f7*

🔴 2 blocking

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `src/ui/identities/update_identity_payout_address.rs`:
- [BLOCKING] lines 274-279: Identity ID used as ProTx hash — likely wrong
  The code passes `self.identity.identity.id().to_string(Encoding::Hex)` as the `pro_tx_hash` parameter to `get_protx_update_registrar`. A Platform Identity ID is NOT the same as a Core ProTx hash. The `protx update_registrar` RPC requires the masternode's ProTx registration hash from Core, not the Platform identity ID. This will cause the RPC call to fail or target the wrong registration.

In `src/backend_task/core/mod.rs`:
- [BLOCKING] lines 144-158: Parameter slots swapped: payout address sent as voting address
  The new screen builds `CoreTask::ProRegUpdateTx(proTxHash, selected_payout_address, selected_funding_address)` but `run_core_task` destructures it as `(pro_tx_hash, voting_address, payout_address)`. The RPC signature is `(..., voting_address, payout_address, fee_source_address)`, so the user's chosen payout address goes into the voting-address slot, and the funding address goes into the payout slot. The feature is broken as written.
```
</details>

2026-03-31 18:48 UTC, thepastaclaw commented on src/ui/identities/update_identity_payout_address.rs
> +                                ),
<!-- thepastaclaw-review v1 finding=9b5440f34564 -->
**🔴 Blocking: Identity ID used as ProTx hash — likely wrong**

The code passes `self.identity.identity.id().to_string(Encoding::Hex)` as the `pro_tx_hash` parameter to `get_protx_update_registrar`. A Platform Identity ID is NOT the same as a Core ProTx hash. The `protx update_registrar` RPC requires the masternode's ProTx registration hash from Core, not the Platform identity ID. This will cause the RPC call to fail or target the wrong registration.

<sub>source: ['claude-general']</sub>

<details>
<summary>🤖 Fix this with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `src/ui/identities/update_identity_payout_address.rs`:
- [BLOCKING] lines 274-279: Identity ID used as ProTx hash — likely wrong
  The code passes `self.identity.identity.id().to_string(Encoding::Hex)` as the `pro_tx_hash` parameter to `get_protx_update_registrar`. A Platform Identity ID is NOT the same as a Core ProTx hash. The `protx update_registrar` RPC requires the masternode's ProTx registration hash from Core, not the Platform identity ID. This will cause the RPC call to fail or target the wrong registration.
```
</details>

2026-03-31 18:48 UTC, thepastaclaw commented on src/backend_task/core/mod.rs
> +                .map_err(|e| e.to_string()),
<!-- thepastaclaw-review v1 finding=d4ae5b90c5a0 -->
**🔴 Blocking: Parameter slots swapped: payout address sent as voting address**

The new screen builds `CoreTask::ProRegUpdateTx(proTxHash, selected_payout_address, selected_funding_address)` but `run_core_task` destructures it as `(pro_tx_hash, voting_address, payout_address)`. The RPC signature is `(..., voting_address, payout_address, fee_source_address)`, so the user's chosen payout address goes into the voting-address slot, and the funding address goes into the payout slot. The feature is broken as written.

<sub>source: ['claude-general', 'codex-general']</sub>

<details>
<summary>🤖 Fix this with AI agents</summary>

```
These findings are from an automated code review. Verify each finding against the current code and only fix it if needed.

In `src/backend_task/core/mod.rs`:
- [BLOCKING] lines 144-158: Parameter slots swapped: payout address sent as voting address
  The new screen builds `CoreTask::ProRegUpdateTx(proTxHash, selected_payout_address, selected_funding_address)` but `run_core_task` destructures it as `(pro_tx_hash, voting_address, payout_address)`. The RPC signature is `(..., voting_address, payout_address, fee_source_address)`, so the user's chosen payout address goes into the voting-address slot, and the funding address goes into the payout slot. The feature is broken as written.
```
</details>

2026-04-01 10:57 UTC, lklimek commented
outdated

2026-04-01 10:57 UTC, closed without merging